BEGIN TRANSACTION;
DELETE FROM suggestions;
INSERT INTO suggestions (Field, Entry) VALUES ("daten_grundlagen_bezeichnung", "Art. 6 (1) a) - Einwilligung");
INSERT INTO suggestions (Field, Entry) VALUES ("daten_grundlagen_bezeichnung", "Art. 6 (1) b) - Vertragserfüllung");
INSERT INTO suggestions (Field, Entry) VALUES ("daten_grundlagen_bezeichnung", "Art. 6 (1) c) - Rechtliche Verpflichtung");
INSERT INTO suggestions (Field, Entry) VALUES ("daten_grundlagen_bezeichnung", "Art. 6 (1) d) - Lebenswichtige Interessen");
INSERT INTO suggestions (Field, Entry) VALUES ("daten_grundlagen_bezeichnung", "Art. 6 (1) e) - Öffentliches Interesse");
INSERT INTO suggestions (Field, Entry) VALUES ("daten_grundlagen_bezeichnung", "Art. 6 (1) f) - Berechtigte Interessen");
INSERT INTO suggestions (Field, Entry) VALUES ("daten_kategorien_beschreibung", "Name");
INSERT INTO suggestions (Field, Entry) VALUES ("daten_kategorien_beschreibung", "E-Mail");
INSERT INTO suggestions (Field, Entry) VALUES ("daten_kategorien_beschreibung", "Kennung");
INSERT INTO suggestions (Field, Entry) VALUES ("daten_kategorien_beschreibung", "Anschrift");
INSERT INTO suggestions (Field, Entry) VALUES ("daten_personen_betroffene", "Rektorat");
INSERT INTO suggestions (Field, Entry) VALUES ("daten_personen_betroffene", "Hochschulrat");
INSERT INTO suggestions (Field, Entry) VALUES ("daten_personen_betroffene", "Dekane");
INSERT INTO suggestions (Field, Entry) VALUES ("daten_personen_betroffene", "Professoren");
INSERT INTO suggestions (Field, Entry) VALUES ("daten_personen_betroffene", "Juniorprofessoren");
INSERT INTO suggestions (Field, Entry) VALUES ("daten_personen_betroffene", "Wissenschaftliche Mitarbeiter");
INSERT INTO suggestions (Field, Entry) VALUES ("daten_personen_betroffene", "Künstlerische Mitarbeiter");
INSERT INTO suggestions (Field, Entry) VALUES ("daten_personen_betroffene", "Mitarbeiter");
INSERT INTO suggestions (Field, Entry) VALUES ("daten_personen_betroffene", "Nebenberufliche Professoren");
INSERT INTO suggestions (Field, Entry) VALUES ("daten_personen_betroffene", "Entpflichtete Professoren");
INSERT INTO suggestions (Field, Entry) VALUES ("daten_personen_betroffene", "Privatdozenten");
INSERT INTO suggestions (Field, Entry) VALUES ("daten_personen_betroffene", "Studierende");
INSERT INTO suggestions (Field, Entry) VALUES ("daten_personen_betroffene", "Wissenschaftliche Hilfskräfte");
INSERT INTO suggestions (Field, Entry) VALUES ("daten_personen_betroffene", "Ehrenbürger");
INSERT INTO suggestions (Field, Entry) VALUES ("daten_personen_betroffene", "Ehrensenatoren");
INSERT INTO suggestions (Field, Entry) VALUES ("daten_personen_betroffene", "Zweithörer");
INSERT INTO suggestions (Field, Entry) VALUES ("daten_personen_betroffene", "Gasthörer");
INSERT INTO suggestions (Field, Entry) VALUES ("daten_personen_betroffene", "Alumni");
INSERT INTO suggestions (Field, Entry) VALUES ("daten_personen_betroffene", "Studienbewerber");
INSERT INTO suggestions (Field, Entry) VALUES ("daten_personen_betroffene", "Bewerber um eine Beschäftigung");
INSERT INTO suggestions (Field, Entry) VALUES ("daten_personen_betroffene", "Ausgeschiedene Mitglieder");
INSERT INTO suggestions (Field, Entry) VALUES ("daten_personen_betroffene", "Ausgeschiedene Angehörige");
INSERT INTO suggestions (Field, Entry) VALUES ("daten_personen_betroffene", "Förderer, Fördergesellschaften");
INSERT INTO suggestions (Field, Entry) VALUES ("daten_personen_betroffene", "Kooperationen");
INSERT INTO suggestions (Field, Entry) VALUES ("daten_personen_betroffene", "Sonstige");
INSERT INTO suggestions (Field, Entry) VALUES ("daten_personen_betroffene", "Ausgründungen");
INSERT INTO suggestions (Field, Entry) VALUES ("daten_personen_betroffene", "An-Institute,");
INSERT INTO suggestions (Field, Entry) VALUES ("daten_personen_betroffene", "Geschäftspartner, Kunden, Lieferanten");
END TRANSACTION;
